### ISSUE TITLE
キャラクターの配置

### ISSUE THREAD

**Issue by takuya-13068** [yodai49/mypic#264]
道中にいるキャラクターの配置を行う

**Comment by takuya-13068** [comment]
他欲しいところありますかね

**Comment by yodai49** [comment]
砂漠の入り口の店の店員欲しいかもしれん
ままザマスはいらない
家の前とか大通りのとことかちょい多めに通行人的なのいても良いかも

**Comment by takuya-13068** [comment]
結局人動かすと変なところで止まるんだけどそれはどうするの

**Comment by takuya-13068** [comment]
暫定的に完了した追加要望はここに書いてね
